# Generated by Django 5.0.6 on 2024-05-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lon", models.FloatField(editable=False)),
                ("lat", models.FloatField(editable=False)),
                ("city_name", models.TextField(editable=False)),
                ("country_code", models.TextField(editable=False, null=True)),
                ("city_raw", models.JSONField(editable=False)),
                ("created_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "City",
                "managed": True,
                "unique_together": {("lon", "lat")},
            },
        ),
        migrations.CreateModel(
            name="CityWeather",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("current_temperature_K", models.FloatField()),
                ("current_condition", models.TextField()),
                ("weather_raw", models.JSONField()),
                ("created_at", models.DateTimeField(null=True)),
                ("last_updated", models.DateTimeField(null=True)),
                (
                    "city",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="city_weather.city",
                    ),
                ),
            ],
            options={
                "db_table": "CityWeather",
                "managed": True,
            },
        ),
    ]
