# Generated by Django 5.0.6 on 2024-06-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city_weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.TextField(editable=False, null=True),
        ),
    ]
